from typing import Protocol
from uuid import UUID


class MinioServiceProtocol(Protocol):
    async def upload_image(self, campaign_id: UUID, image_data: bytes) -> str: ...
    async def delete_image(self, campaign_id: UUID) -> None: ...
    async def get_image_url(self, campaign_id: UUID) -> str | None: ...
