test_name: Проверка AI генерации

stages:
  - name: 'Создание рекламодателя для тестов'
    request:
      url: '{BASE_URL}/advertisers/bulk'
      method: POST
      json:
        - !include components/advertisers/advertiser1.yml
    response:
      status_code: 201

  - name: 'Создание рекламной кампании для тестов'
    request:
      url: '{BASE_URL}/advertisers/e14e523e-7bc0-4340-b096-22b669b49a20/campaigns'
      method: POST
      json: !include components/campaigns/campaign1.yml
    response:
      status_code: 201
      save:
        json:
          test_campaign_id: campaign_id

  - name: 'Генерация рекламного текста'
    request:
      url: '{BASE_URL}/generate-ad'
      method: GET
      params:
        advertiser_id: e14e523e-7bc0-4340-b096-22b669b49a20
        ad_title: "Новая коллекция спортивной одежды"
    response:
      status_code: 200
      json:
        generated_text: !anystr

  - name: 'Генерация изображения для кампании'
    request:
      url: '{BASE_URL}/generate-image'
      method: GET
      params:
        campaign_id: '{test_campaign_id}'
    response:
      status_code: 200 